import { NextResponse } from 'next/server';
import { getSupabaseAdmin } from '@/lib/supabase-server';

export const dynamic = 'force-dynamic';

export async function POST(
  req: Request,
  { params }: { params: { id: string } }
) {
  const body = await req.json();
  const supabase = getSupabaseAdmin();

  if (!body.workspace_id) {
    return NextResponse.json({ error: 'workspace_id required' }, { status: 400 });
  }

  const { data: workflow } = await supabase
    .from('workflows')
    .select('*')
    .eq('id', params.id)
    .eq('workspace_id', body.workspace_id)
    .maybeSingle();

  if (!workflow) {
    return NextResponse.json({ error: 'Workflow not found' }, { status: 404 });
  }

  const { data: steps } = await supabase
    .from('workflow_steps')
    .select('*')
    .eq('workflow_id', params.id)
    .order('step_order', { ascending: true });

  if (!steps || steps.length === 0) {
    return NextResponse.json({ error: 'Workflow has no steps' }, { status: 400 });
  }

  const { data: run, error: runError } = await supabase
    .from('workflow_runs')
    .insert({
      workspace_id: body.workspace_id,
      workflow_id: params.id,
      run_date: new Date().toISOString().split('T')[0],
      status: 'SUCCESS',
    })
    .select()
    .single();

  if (runError) {
    return NextResponse.json({ error: runError.message }, { status: 500 });
  }

  const { data: leads } = await supabase
    .from('leads')
    .select('id, name, assigned_to, status')
    .eq('workspace_id', body.workspace_id)
    .in('status', ['new', 'in_progress']);

  const targetLeads = leads || [];
  const errors: string[] = [];
  let tasksCreated = 0;
  let leadsUpdated = 0;
  let activitiesAdded = 0;

  for (const step of steps) {
    try {
      const config = step.config as Record<string, any>;

      if (step.step_type === 'CREATE_TASK') {
        if (targetLeads.length > 0 && config.title_template?.includes('{lead_name}')) {
          for (const lead of targetLeads) {
            const title = (config.title_template as string).replace('{lead_name}', lead.name);
            const dueAt = new Date();
            dueAt.setDate(dueAt.getDate() + (config.due_offset_days || 0));

            await supabase.from('tasks').insert({
              workspace_id: body.workspace_id,
              title,
              description: `Auto-generated by workflow: ${workflow.name}`,
              type: config.type || 'GENERAL',
              status: 'TODO',
              priority: config.priority || 'MEDIUM',
              due_at: dueAt.toISOString(),
              assigned_to_user_id: config.assign_rule === 'lead_owner' ? lead.assigned_to : null,
              lead_id: lead.id,
              workflow_run_id: run.id,
            });
            tasksCreated++;
          }
        } else {
          const dueAt = new Date();
          dueAt.setDate(dueAt.getDate() + (config.due_offset_days || 0));

          await supabase.from('tasks').insert({
            workspace_id: body.workspace_id,
            title: config.title_template || 'Untitled Task',
            description: `Auto-generated by workflow: ${workflow.name}`,
            type: config.type || 'GENERAL',
            status: 'TODO',
            priority: config.priority || 'MEDIUM',
            due_at: dueAt.toISOString(),
            assigned_to_user_id: null,
            lead_id: null,
            workflow_run_id: run.id,
          });
          tasksCreated++;
        }
      }

      if (step.step_type === 'UPDATE_LEAD') {
        for (const lead of targetLeads) {
          const updateData: Record<string, any> = { updated_at: new Date().toISOString() };
          if (config.new_status) updateData.status = config.new_status;

          await supabase.from('leads').update(updateData).eq('id', lead.id);
          leadsUpdated++;
        }
      }

      if (step.step_type === 'ADD_ACTIVITY') {
        for (const lead of targetLeads) {
          const note = (config.note_template as string || '').replace('{lead_name}', lead.name);
          await supabase.from('activity_logs').insert({
            workspace_id: body.workspace_id,
            lead_id: lead.id,
            user_id: null,
            action: 'Workflow Note',
            type: config.type || 'note',
            description: note || `Workflow "${workflow.name}" executed`,
          });
          activitiesAdded++;
        }
      }
    } catch (err: any) {
      errors.push(`Step ${step.step_order}: ${err.message}`);
    }
  }

  if (errors.length > 0) {
    await supabase
      .from('workflow_runs')
      .update({ status: 'FAILED' })
      .eq('id', run.id);
  }

  return NextResponse.json({
    run_id: run.id,
    status: errors.length > 0 ? 'FAILED' : 'SUCCESS',
    tasks_created: tasksCreated,
    leads_updated: leadsUpdated,
    activities_added: activitiesAdded,
    errors,
  });
}
